<?php get_header(); ?>
<main id="main-content" class="v5-home">
<section class="v5-hero">
  <div class="v5-grid"></div><div class="v5-aurora"></div>
  <div class="k-container v5-hero-inner">
    <div class="v5-hero-copy reveal">
      <div class="v5-kicker"><span class="live-dot"></span> Conversational AI for real business actions</div>
      <h1>Conversations that<br><span>turn into action.</span></h1>
      <p>Deploy intelligent AI agents that speak naturally, understand intent and complete customer-facing tasks across voice, calendars, messaging and your business systems.</p>
      <div class="hero-actions"><a class="k-btn k-btn-primary" href="#talk">● Talk to KATHYA</a><a class="v5-text-link" href="#studio">Build an agent <span>↗</span></a></div>
      <div class="v5-proof"><span>Natural voice</span><span>Multilingual</span><span>Connected actions</span><span>Human handoff</span></div>
    </div>
    <div class="v5-product-stage reveal" id="talk">
      <div class="v5-console v8-console">
        <div class="v5-console-head"><div><i></i><strong>KATHYA LIVE</strong></div><span>CONVERSATION → ACTION</span></div>
        <div class="v8-demo-grid">
          <div class="v8-orb-zone">
            <div class="v8-orbit o1"></div><div class="v8-orbit o2"></div>
            <div class="v5-core v8-core"><b>K</b></div>
            <div class="v5-wave v8-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>
            <small id="v5-status">Ready for a request</small>
          </div>
          <div class="v8-journey">
            <div class="v8-step active"><b>01</b><span><small>LISTEN</small><strong>Customer request</strong></span></div>
            <div class="v8-step"><b>02</b><span><small>UNDERSTAND</small><strong>Intent + context</strong></span></div>
            <div class="v8-step"><b>03</b><span><small>ACT</small><strong>Check connected tools</strong></span></div>
            <div class="v8-step"><b>04</b><span><small>COMPLETE</small><strong>Confirm the outcome</strong></span></div>
          </div>
        </div>
        <div class="v5-chat v8-chat" id="v5-chat"><div class="user"><small>YOU</small><p>Can you book a demo tomorrow afternoon?</p></div><div class="ai"><small>KATHYA</small><p>Absolutely. I can check availability and help you choose a time.</p></div></div>
        <div class="v8-action-strip"><span>Intent <b id="v8-intent">Appointment</b></span><span>Tool <b id="v8-tool">Calendar</b></span><span>Next action <b id="v8-next">Find availability</b></span></div>
        <div class="v5-actions"><button id="v5-talk" type="button"><span>●</span> Experience KATHYA</button><a href="<?php echo esc_url(home_url('/book-appointment/')); ?>">Book directly →</a></div>
      </div>
    </div>
  </div>
</section>
<section class="v5-marquee"><div class="k-container"><span>VOICE</span><i>✦</i><span>KNOWLEDGE</span><i>✦</i><span>REASONING</span><i>✦</i><span>ACTIONS</span><i>✦</i><span>ANALYTICS</span><i>✦</i><span>HUMAN HANDOFF</span></div></section>
<section class="v5-section v5-outcome"><div class="k-container"><div class="v5-section-head reveal"><span>HOW KATHYA WORKS</span><h2>One conversation.<br>Real action.</h2><p>Voice is the interface. Business outcomes are the product.</p></div><div class="v5-flow reveal"><article><b>01</b><h3>Speak</h3><p>Natural conversation</p><em>“I need an appointment.”</em></article><article><b>02</b><h3>Understand</h3><p>Intent + context</p><em>Appointment request</em></article><article><b>03</b><h3>Reason</h3><p>Rules + knowledge</p><em>Check availability</em></article><article><b>04</b><h3>Act</h3><p>Connected tools</p><em>4:00 PM booked</em></article><article class="active"><b>05</b><h3>Result</h3><p>Outcome captured</p><em>✓ Email&nbsp;&nbsp; ✓ Calendar</em></article></div></div></section>
<section class="v5-section v5-bento-section"><div class="k-container"><div class="v5-section-head reveal"><span>THE PLATFORM</span><h2>Built to do more than talk.</h2></div><div class="v5-bento v5-bento-live">
<article class="bento-wide"><div><span class="v5-label">NATURAL CONVERSATION</span><h3>Voice that feels present.</h3><p>Design responsive conversations around your business, knowledge and customer journey.</p></div><div class="bento-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></article>
<article class="bento-stat"><span class="v5-label">ALWAYS AVAILABLE</span><strong>24<span>/7</span></strong><p>Handle customer conversations beyond business hours.</p></article>
<article class="bento-lang"><span class="v5-label">MULTILINGUAL</span><h3>Speak their language.</h3><div><b>EN</b><b>HI</b><b>ES</b><b>TE</b><b>TA</b><b>+</b></div><p>Language availability depends on your configured production voice stack.</p></article>
<article class="bento-actions"><span class="v5-label">BUSINESS ACTIONS</span><h3>Conversation → completion.</h3><ul><li><span>Calendar</span><b>Connected</b></li><li><span>Email</span><b>Connected</b></li><li><span>WhatsApp</span><b>Integration ready</b></li><li><span>CRM / API</span><b>Connect</b></li></ul></article>
<article class="bento-intel"><span class="v5-label">CONVERSATION INTELLIGENCE</span><div class="intel-top"><h3>Every outcome, visible.</h3><span>Today</span></div><div class="intel-metrics"><div><small>Conversations</small><strong>1,284</strong></div><div><small>Completed</small><strong>942</strong></div><div><small>Resolution</small><strong>73%</strong></div></div><div class="intel-chart"><i style="height:32%"></i><i style="height:46%"></i><i style="height:41%"></i><i style="height:63%"></i><i style="height:55%"></i><i style="height:78%"></i><i style="height:71%"></i><i style="height:88%"></i><i style="height:82%"></i><i style="height:96%"></i></div><small class="v5-demo-note">Illustrative product preview</small></article>
</div></div></section>
<section class="v5-section v5-studio" id="studio"><div class="k-container v5-studio-grid"><div class="reveal"><span class="v5-eyebrow">KATHYA STUDIO</span><h2>Describe the agent.<br>KATHYA does the rest.</h2><p>Move from idea to a configured AI experience through a simple, visual workflow.</p><div class="v5-step-list"><span class="active">01 Purpose</span><span>02 Voice</span><span>03 Knowledge</span><span>04 Actions</span><span>05 Test</span></div></div><div class="v5-builder reveal"><div class="v5-builder-top"><span>New agent</span><i>Draft</i></div><label>What should your agent do?</label><textarea id="v5-prompt">Answer customer calls, explain our services and book appointments.</textarea><div class="v5-builder-row"><div><small>INDUSTRY</small><select id="v5-industry"><option>Professional Services</option><option>Healthcare Administration</option><option>Real Estate</option><option>Hospitality</option><option>Automotive</option><option>Education</option></select></div><div><small>LANGUAGE</small><select><option>English</option><option>English + Hindi</option><option>English + Spanish</option></select></div></div><button id="v5-build" class="k-btn k-btn-primary" type="button">Generate agent →</button><div class="v5-agent-result" id="v5-result"><span class="v5-agent-avatar">K</span><div><small>YOUR AGENT</small><strong>KATHYA Assistant</strong><p>Voice • Knowledge • Calendar • Email</p></div><button type="button">▶ Test</button></div></div></div></section>
<section class="v5-section v5-usecases"><div class="k-container"><div class="v5-section-head reveal"><span>SOLUTIONS</span><h2>Start with the outcome.</h2><p>Configure KATHYA around the job your customers need completed.</p></div><div class="v5-usecase-tabs reveal"><button class="active" data-use="reception">Reception</button><button data-use="sales">Sales</button><button data-use="support">Support</button><button data-use="booking">Appointments</button><button data-use="custom">Custom</button></div><div class="v5-usecase-panel reveal"><div><span class="v5-label" id="use-label">AI RECEPTION</span><h3 id="use-title">Never leave a customer waiting.</h3><p id="use-copy">Answer, understand, route and complete routine customer requests around the clock.</p><a href="<?php echo esc_url(home_url('/solutions/')); ?>">Explore solutions →</a></div><div class="v5-mini-call"><header><span><i></i> KATHYA</span><small>00:42</small></header><p><b>Customer</b> “I'd like to move my appointment to Friday.”</p><p class="green"><b>KATHYA</b> “Of course. I found your booking and have two times available Friday.”</p><footer><span>Customer recognized</span><span>Calendar checked</span><span>Ready to reschedule</span></footer></div></div></div></section>
<section class="v5-section v5-connect"><div class="k-container v5-connect-grid"><div class="reveal"><span class="v5-eyebrow">CONNECTED BUSINESS</span><h2>KATHYA fits into the systems you already use.</h2><p>Connect conversations to calendars, messaging, CRM workflows, email and custom APIs. Mark integrations as live only after production configuration.</p><a class="v5-text-link" href="<?php echo esc_url(home_url('/integrations/')); ?>">Explore integrations →</a></div><div class="v5-network reveal"><div class="hub">K<span>AI</span></div><div class="node n1">Calendar</div><div class="node n2">WhatsApp</div><div class="node n3">Email</div><div class="node n4">CRM</div><div class="node n5">API</div><div class="node n6">Webhooks</div></div></div></section>
<section class="v5-section v5-trust"><div class="k-container"><div class="v5-trust-card reveal"><div><span class="v5-eyebrow">TRUST BY DESIGN</span><h2>AI conversations need clear controls.</h2><p>Build trust with transparent data handling, access controls, consent, AI disclosure and human escalation.</p></div><div class="v5-trust-points"><span>Privacy</span><span>Consent</span><span>Access controls</span><span>Human handoff</span></div><a class="k-btn k-btn-ghost" href="<?php echo esc_url(home_url('/trust/')); ?>">Trust Center →</a></div></div></section>
<section class="v5-section v5-book"><div class="k-container v5-book-card reveal"><div><span class="v5-eyebrow">READY WHEN YOU ARE</span><h2>Turn the next conversation<br>into action.</h2><p>Experience KATHYA and explore a workflow for your business.</p></div><div><a class="k-btn k-btn-primary" href="<?php echo esc_url(home_url('/demo/')); ?>">Talk to KATHYA →</a><a class="v5-text-link" href="<?php echo esc_url(home_url('/book-appointment/')); ?>">Book a meeting</a></div></div></section>
</main>
<?php get_footer(); ?>
