<?php get_header(); ?>
<main><section class="page-hero compact"><div class="k-container"><div class="eyebrow">LIVE DEMO REQUEST</div><h1>Experience KATHYA AI for your business.</h1><p>Tell us what you want the agent to do. This form requests a demo; it does not automatically place a call.</p></div></section>
<section class="k-section"><div class="k-container form-layout"><div><h2>What happens next?</h2><div class="steps-list"><div><b>1</b><p><strong>Choose your AI workflow</strong><span>Sales, support, reception, appointments or a custom workflow.</span></p></div><div><b>2</b><p><strong>We map the workflow</strong><span>Questions, knowledge, actions and handoff.</span></p></div><div><b>3</b><p><strong>Experience a tailored demo</strong><span>Hear how the conversation could work for your business.</span></p></div></div><div class="compliance-box"><strong>Responsible outreach</strong><p>Use outbound calling only where you have the required consent and comply with applicable telecom, privacy, recording and marketing rules.</p></div></div>
<form class="k-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
<input type="hidden" name="action" value="kathya_demo"><?php wp_nonce_field('kathya_demo_submit','kathya_demo_nonce'); ?>
<?php if (isset($_GET['demo']) && $_GET['demo']==='success'): ?><div class="form-success">Thank you. Your demo request was sent.</div><?php elseif(isset($_GET['demo']) && $_GET['demo']==='email-error'): ?><div class="form-error">Your request could not be emailed. Please try again or contact us directly.</div><?php elseif(isset($_GET['demo'])): ?><div class="form-error">Please complete all required fields and consent.</div><?php endif; ?>
<label>Name *<input name="name" required></label><label>Work email *<input type="email" name="email" required></label><label>Phone *<input name="phone" required></label><label>Company<input name="company"></label><label>AI teammate<select name="agent"><option>KATHYA Reception</option><option>KATHYA Sales</option><option>KATHYA Support</option><option>KATHYA Book</option><option>Custom workflow</option></select></label><label>Preferred language<select name="language"><option>English</option><option>English + Hindi</option><option>English + Telugu</option><option>English + Tamil</option><option>English + Spanish</option><option>Other</option></select></label><label class="check"><input type="checkbox" name="consent" value="1" required><span>I agree to be contacted about this demo request. *</span></label><button class="k-btn k-btn-primary" type="submit">Request Demo →</button><small>Configure SMTP in WordPress so form emails are delivered reliably.</small>
<div class="hp-field" aria-hidden="true"><label>Website <input type="text" name="website" tabindex="-1" autocomplete="off"></label></div></form></div></section></main>
<?php get_footer(); ?>
