<?php get_header(); ?>
<main><section class="page-hero"><div class="k-container"><div class="eyebrow">SOLUTIONS</div><h1>Conversational AI built around business outcomes.</h1><p>Start with a customer workflow, then connect the knowledge and tools KATHYA needs to complete it.</p></div></section>
<section class="k-section"><div class="k-container solution-stack">
<article id="reception"><div><span>01</span><h2>KATHYA Reception</h2><p>Handle routine inbound conversations, capture details, route requests and schedule appointments.</p><ul class="check-list"><li>24/7 call handling</li><li>Customer inquiry capture</li><li>Routing and transfer logic</li><li>Message capture</li><li>Calendar-ready workflows</li></ul></div><div class="feature-panel"><b>Call arrives</b><i>↓</i><b>Request understood</b><i>↓</i><b>Action selected</b><i>↓</i><b>Book or route</b><i>↓</i><b>Summary saved</b></div></article>
<article id="sales"><div><span>02</span><h2>KATHYA Sales</h2><p>Engage inbound or properly consented outbound leads, qualify interest and schedule meetings.</p><ul class="check-list"><li>Lead qualification</li><li>FAQ and objection handling</li><li>Meeting scheduling</li><li>CRM-ready structured outcomes</li><li>Follow-up triggers</li></ul></div><div class="feature-panel"><b>Lead responds</b><i>↓</i><b>KATHYA qualifies</b><i>↓</i><b>Need identified</b><i>↓</i><b>Meeting booked</b><i>↓</i><b>CRM updated</b></div></article>
<article id="support"><div><span>03</span><h2>KATHYA Support</h2><p>Resolve repeat customer requests and bring humans into the conversation when judgment is needed.</p><ul class="check-list"><li>Knowledge-based answers</li><li>Intent and issue classification</li><li>Conversation summaries</li><li>Escalation rules</li><li>Human transfer with context</li></ul></div><div class="feature-panel"><b>Customer calls</b><i>↓</i><b>Intent identified</b><i>↓</i><b>Issue handled</b><i>↓</i><b>Escalate if needed</b><i>↓</i><b>Outcome logged</b></div></article>
<article id="book"><div><span>04</span><h2>KATHYA Book</h2><p>Turn appointment and reservation conversations into structured scheduling actions.</p><ul class="check-list"><li>Availability requests</li><li>Appointment booking</li><li>Rescheduling and cancellations</li><li>Confirmations and reminders</li><li>Calendar integration ready</li></ul></div><div class="feature-panel"><b>Request received</b><i>↓</i><b>Availability checked</b><i>↓</i><b>Time selected</b><i>↓</i><b>Booking confirmed</b><i>↓</i><b>Follow-up triggered</b></div></article>
</div></section></main>
<?php get_footer(); ?>
