<?php get_header(); ?>
<main class="pricing-page">
<section class="page-hero pricing-hero"><div class="k-container"><div class="eyebrow">KATHYA PRICING</div><h1>Simple pricing for conversations that take action.</h1><p>Start with one workflow, then scale across voice, knowledge, business actions and integrations. India and global rates are regional prices, not currency conversions.</p></div></section>
<section class="k-section pricing-section"><div class="k-container">
<div class="kathya-region-bar"><span>INDIA <b>₹ INR</b></span><span>GLOBAL <b>$ USD</b></span><em>Usage-based • scale-friendly</em></div>
<div class="pricing-grid pricing-compare kathya-pricing-v9">
<div class="price-card"><span>Launch</span><div class="dual-price"><strong>₹4.49<small>/min</small></strong><b>$0.049<small>/min</small></b></div><p>For pilots, startups and focused customer workflows.</p><ul><li>AI voice agent</li><li>Knowledge + intent handling</li><li>Standard workflow actions</li><li>Transcripts + basic analytics</li><li>Email support</li></ul><a class="k-btn k-btn-ghost" href="<?php echo esc_url(home_url('/get-started/?plan=launch')); ?>">Start with Launch</a></div>
<div class="price-card featured"><div class="popular">POPULAR</div><span>Growth</span><div class="dual-price"><strong>₹3.99<small>/min</small></strong><b>$0.045<small>/min</small></b></div><p>For growing businesses connecting conversations to more systems.</p><ul><li>Everything in Launch</li><li>Multiple agents + workflows</li><li>Calendar / CRM / API actions</li><li>Outcome analytics</li><li>Priority onboarding</li></ul><a class="k-btn k-btn-primary" href="<?php echo esc_url(home_url('/demo/?plan=growth')); ?>">Talk to KATHYA</a></div>
<div class="price-card"><span>Scale</span><div class="dual-price"><strong>₹3.49<small>/min</small></strong><b>$0.039<small>/min</small></b></div><p>For higher-volume operations and deeper automation.</p><ul><li>Everything in Growth</li><li>Advanced integrations</li><li>Custom action logic</li><li>Human handoff context</li><li>Priority support</li></ul><a class="k-btn k-btn-ghost" href="<?php echo esc_url(home_url('/contact/?plan=scale')); ?>">Discuss Scale</a></div>
<div class="price-card"><span>Enterprise</span><div class="dual-price"><strong>Custom</strong><b>Custom</b></div><p>For specialized architecture, volume and commercial requirements.</p><ul><li>Custom volume pricing</li><li>Deployment planning</li><li>Security review</li><li>Commercial SLA options</li><li>Dedicated solution design</li></ul><a class="k-btn k-btn-ghost" href="<?php echo esc_url(home_url('/contact/?plan=enterprise')); ?>">Contact sales</a></div>
</div>
<div class="kathya-pricing-story"><div><span class="eyebrow">WHY KATHYA</span><h2>Pay for the conversation.<br>Build for the outcome.</h2></div><div class="kathya-pricing-points"><span><b>Understand</b>Intent + context</span><span><b>Reason</b>Knowledge + rules</span><span><b>Act</b>Connected workflows</span><span><b>Complete</b>Outcome + handoff</span></div></div>
<div class="pricing-note"><strong>Clear billing:</strong> rates above are KATHYA regional usage prices. Telephony/carrier, phone-number rental, premium voices/models, messaging fees or specialized third-party services may be billed separately when used. Final production pricing depends on configuration and committed volume.</div>
</div></section>
</main>
<?php get_footer(); ?>