-- KATHYA multi-tenant application schema (Supabase/Postgres)
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text,business_name text,mobile text,primary_goal text,onboarding_complete boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.agents(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,status text not null default 'draft',channel text,config jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.conversations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,agent_id uuid references public.agents(id) on delete set null,channel text,status text not null default 'open',summary text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.billing_accounts(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,plan text not null default 'launch',provider_customer_id text,subscription_status text not null default 'inactive',usage_minutes numeric not null default 0,updated_at timestamptz not null default now());
create table if not exists public.user_settings(user_id uuid primary key references auth.users(id) on delete cascade,timezone text,notifications jsonb not null default '{}'::jsonb,preferences jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create index if not exists agents_user_id_idx on public.agents(user_id);create index if not exists conversations_user_id_idx on public.conversations(user_id);create index if not exists conversations_agent_id_idx on public.conversations(agent_id);
alter table public.profiles enable row level security;alter table public.agents enable row level security;alter table public.conversations enable row level security;alter table public.billing_accounts enable row level security;alter table public.user_settings enable row level security;
revoke all on public.profiles,public.agents,public.conversations,public.billing_accounts,public.user_settings from anon;grant select,insert,update,delete on public.profiles,public.agents,public.conversations,public.user_settings to authenticated;grant select on public.billing_accounts to authenticated;
do $$ declare t text; begin foreach t in array array['profiles','agents','conversations','billing_accounts','user_settings'] loop execute format('drop policy if exists "own_select" on public.%I',t);execute format('create policy "own_select" on public.%I for select to authenticated using ((select auth.uid()) = %s)',t,case when t in ('profiles','user_settings') then case when t='profiles' then 'id' else 'user_id' end else 'user_id' end); end loop; end $$;
create policy "own_insert" on public.profiles for insert to authenticated with check ((select auth.uid())=id);create policy "own_update" on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy "own_insert" on public.agents for insert to authenticated with check ((select auth.uid())=user_id);create policy "own_update" on public.agents for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);create policy "own_delete" on public.agents for delete to authenticated using ((select auth.uid())=user_id);
create policy "own_insert" on public.conversations for insert to authenticated with check ((select auth.uid())=user_id);create policy "own_update" on public.conversations for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);create policy "own_delete" on public.conversations for delete to authenticated using ((select auth.uid())=user_id);
create policy "own_insert" on public.user_settings for insert to authenticated with check ((select auth.uid())=user_id);create policy "own_update" on public.user_settings for update to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing;insert into public.user_settings(user_id) values(new.id) on conflict(user_id) do nothing;insert into public.billing_accounts(user_id) values(new.id) on conflict(user_id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- KATHYA privileged admin authorization. Never expose role assignment in client UI.
create table if not exists public.admin_users(user_id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in('owner','admin','support','billing')),created_at timestamptz not null default now());
alter table public.admin_users enable row level security;
revoke all on public.admin_users from anon,authenticated;
create or replace function public.is_kathya_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.admin_users where user_id=auth.uid() and role in('owner','admin')); $$;
revoke all on function public.is_kathya_admin() from public;grant execute on function public.is_kathya_admin() to authenticated;
-- Assign the first owner only from the Supabase SQL editor after that person's verified auth account exists:
-- insert into public.admin_users(user_id,role) select id,'owner' from auth.users where email='OWNER_EMAIL' on conflict(user_id) do update set role='owner';
