export const pages={
product:{eyebrow:'PRODUCT',title:'Conversation intelligence that moves work forward.',copy:'Build AI experiences that understand intent, reason over business context, connect tools, execute workflows and complete measurable customer outcomes.',cards:[['Natural conversation','Responsive voice and digital conversations shaped around your business.'],['Reasoning','Use context, knowledge, policy and workflow rules to decide the next action.'],['Connected actions','Connect calendars, CRM, messaging, APIs and webhooks to execute real work.'],['Human handoff','Escalate with useful context when a person should take over.']]},
solutions:{eyebrow:'SOLUTIONS',title:'Start with the outcome.',copy:'Configure KATHYA around the job your customers need completed.',cards:[['AI Receptionist','Answer, understand and route customer requests.'],['Sales Agent','Qualify interest and move the next step forward.'],['Customer Support','Resolve routine questions and escalate with context.'],['Appointments','Move from request to availability and confirmation.'],['Customer Engagement','Run structured conversations for updates and follow-up.'],['Custom AI Agents','Design a workflow around your own business process.']]},
industries:{eyebrow:'INDUSTRIES',title:'Adapt KATHYA to the way your business works.',copy:'Use one conversational layer across customer journeys while keeping workflows, knowledge and actions specific to your operation.',cards:[['Professional Services','Handle inquiries, qualification and appointment workflows.'],['Healthcare Administration','Support administrative conversations and scheduling workflows.'],['Real Estate','Respond to inquiries, qualify interest and coordinate appointments.'],['Hospitality','Handle common guest questions and service requests.'],['Automotive','Support inquiries, service scheduling and follow-up.'],['Education','Guide inquiries and route next steps.']]},
integrations:{eyebrow:'INTEGRATIONS',title:'Connect conversation to action.',copy:'KATHYA is designed to work with the systems that already run your customer operations.',cards:[['Calendars','Availability, booking and scheduling workflows.'],['CRM','Read and update customer workflow context.'],['Email','Send confirmations and operational messages.'],['Messaging','Connect supported messaging channels as configured.'],['APIs','Call business services and custom endpoints.'],['Webhooks','Trigger downstream workflows from conversation events.']]},
developers:{eyebrow:'DEVELOPERS',title:'Build KATHYA into your product and workflows.',copy:'A developer surface for agents, actions, events and business integrations.',cards:[['Agent configuration','Define purpose, behavior, knowledge and controls.'],['Actions','Connect business functions to conversational intent.'],['Events','Use webhooks for workflow and analytics events.'],['Testing','Validate agent behavior before production rollout.']]},
resources:{eyebrow:'RESOURCES & BLOG',title:'Learn how conversational AI becomes operational.',copy:'Practical resources for teams evaluating, designing and deploying customer-facing AI workflows.',cards:[['Getting started','Plan your first conversational AI workflow around one measurable outcome.'],['Conversation design','Patterns for natural journeys built around customer intent and clear next steps.'],['Integration guides','Connect actions to calendars, CRM, messaging and business APIs.'],['Trust & controls','Guidance for disclosure, consent, access and human escalation.']]}
};
export const plans=[
['Starter','$49 /month',['1 AI agent','1,000 conversation minutes','Basic integrations','Email support']],
['Professional','$199 /month',['5 AI agents','10,000 conversation minutes','Advanced integrations','Analytics dashboard','Priority support']],
['Business','$499 /month',['20 AI agents','50,000 conversation minutes','Custom integrations','Dedicated success manager','SLA support']],
['Enterprise','Custom',['Unlimited agents','Custom usage volume','Dedicated infrastructure','Advanced security & compliance','24/7 support']]
];