import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Menu,X,ArrowRight,Mic,Calendar,MessageSquare,BarChart3,Workflow,ShieldCheck,Check,ChevronRight}from'lucide-react';import'./styles.css';

const plans=[
{name:'Launch',desc:'A focused pilot for one customer outcome.',items:['1 KATHYA agent','1 core workflow','Outcome analytics','Email support'],cta:'Start a pilot'},
{name:'Growth',desc:'Connect conversations to multiple workflows.',items:['Multiple agents','Calendar / CRM workflows','Advanced outcome tracking','Priority onboarding'],cta:'Book a demo',featured:true},
{name:'Business',desc:'Deeper integrations and operational controls.',items:['Team workflows','Advanced integrations','Custom action logic','Priority support'],cta:'Contact sales'},
{name:'Enterprise',desc:'Specialized, higher-volume deployments.',items:['Custom architecture','Security review','Deployment options','Commercial SLA options'],cta:'Talk to us'}];

function App(){const[menu,setMenu]=useState(false),[step,setStep]=useState(0);
const run=()=>{setStep(1);setTimeout(()=>setStep(2),700);setTimeout(()=>setStep(3),1400);setTimeout(()=>setStep(4),2100)};
return <div className="app">
<header><a className="brand" href="#"><span className="mark">K</span><b>KATHYA <i>AI</i></b></a><nav className={menu?'open':''}>{['Product','Solutions','Industries','Integrations','Pricing','Developers','Resources'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<a href="#signin">Sign in</a><a className="talk" href="#demo">Talk to KATHYA</a></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main>
<section className="hero"><div className="watermark">K</div><div className="heroCopy"><div className="eyebrow"><span/> CONVERSATIONAL AI FOR REAL BUSINESS ACTIONS</div><h1>Conversations that <em>complete the work.</em></h1><p>KATHYA understands customer intent, connects to business systems and moves every conversation toward a clear outcome.</p><div className="actions"><button onClick={run}>Experience KATHYA <ArrowRight size={16}/></button><a href="#studio">Build an agent <ChevronRight size={16}/></a></div><div className="proof"><span>Natural voice</span><span>Business actions</span><span>Human handoff</span></div></div>
<div className="console" id="demo"><div className="consoleTop"><b><span/> KATHYA LIVE</b><small>CONVERSATION → OUTCOME</small></div><div className="messages"><article><small>CUSTOMER</small><p>Can you book a demo tomorrow afternoon?</p></article><article className="ai"><small>KATHYA</small><p>{step<2?'I can check availability and help you choose a time.':step<4?'I’m checking the connected calendar for available times.':'I found two available times. Ready to confirm.'}</p></article></div><div className="flow">{['Listen','Understand','Act','Complete'].map((x,i)=><React.Fragment key={x}><div className={step>=i+1?'active':''}><b>0{i+1}</b><span>{x}</span></div>{i<3&&<i/>}</React.Fragment>)}</div><div className="outcomes"><span><small>INTENT</small><b>{step>=2?'Book demo':'—'}</b></span><span><small>TOOL</small><b>{step>=3?'Calendar':'—'}</b></span><span><small>OUTCOME</small><b>{step>=4?'Times found':'Pending'}</b></span></div><button className="run" onClick={run}><Mic size={16}/> {step===4?'Run again':'Run live workflow'}</button></div></section>
<section className="ticker"><span>VOICE</span><b>✦</b><span>KNOWLEDGE</span><b>✦</b><span>REASONING</span><b>✦</b><span>ACTIONS</span><b>✦</b><span>ANALYTICS</span></section>
<section className="section" id="product"><div className="sectionHead"><small>HOW KATHYA WORKS</small><h2>One conversation.<br/>Real action.</h2></div><div className="steps">{[['01','Speak','Natural conversation'],['02','Understand','Intent + context'],['03','Decide','Rules + knowledge'],['04','Act','Connected tools'],['05','Complete','Outcome captured']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="section bento"><div className="sectionHead"><small>THE PLATFORM</small><h2>Built to do more than talk.</h2></div><div className="bentoGrid"><article className="wide"><Mic/><h3>Natural conversation</h3><p>Responsive conversations shaped around your business, knowledge and customer journey.</p></article><article><Calendar/><h3>Appointments</h3><p>Move from request to availability and confirmation.</p></article><article><Workflow/><h3>Business actions</h3><p>Connect calendars, CRM, messaging and APIs.</p></article><article><MessageSquare/><h3>Omnichannel</h3><p>Design consistent customer journeys across supported channels.</p></article><article className="wide"><BarChart3/><h3>Outcome intelligence</h3><p>See what customers wanted, what KATHYA did and what completed.</p></article></div></section>
<section className="section pricing" id="pricing"><div className="sectionHead"><small>PRICING</small><h2>Start focused. Scale with outcomes.</h2><p>Commercial pricing is tailored to configured channels, usage, integrations and support.</p></div><div className="plans">{plans.map(p=><article className={p.featured?'featured':''} key={p.name}>{p.featured&&<label>RECOMMENDED</label>}<small>{p.name}</small><h3>Custom</h3><p>{p.desc}</p><ul>{p.items.map(i=><li key={i}><Check size={14}/>{i}</li>)}</ul><a href="#contact">{p.cta}<ArrowRight size={15}/></a></article>)}</div></section>
<section className="section trust"><div><ShieldCheck/><small>TRUST BY DESIGN</small><h2>Clear controls for AI conversations.</h2><p>Design for transparent data handling, consent, access control and human escalation.</p></div><a href="#contact">Explore KATHYA <ArrowRight size={16}/></a></section>
</main><footer><a className="brand" href="#"><span className="mark">K</span><b>KATHYA <i>AI</i></b></a><p>Speak. Understand. Act.</p><small>© {new Date().getFullYear()} KATHYA AI · A technology product by PA MedLog Talent LLC.</small></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);