import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowRight,Calendar,ChevronRight,Menu,X,Mic2,MessageSquare,Workflow,BarChart3,ShieldCheck,Globe2,Plug,Check,Play}from'lucide-react';import'./styles.css';

const solutions=[['AI Receptionist','Answer, understand and route customer requests.'],['Appointments','Check availability and move bookings forward.'],['Sales','Qualify intent and guide prospects to the next action.'],['Support','Resolve routine questions and escalate with context.'],['Engagement','Continue conversations across digital channels.'],['Custom Workflows','Connect conversation logic to your business systems.']];
const integrations=[['Calendar',Calendar],['CRM',Workflow],['Messaging',MessageSquare],['Voice',Mic2],['Analytics',BarChart3],['APIs',Plug]];
const plans=[['Launch','One focused workflow',['1 KATHYA agent','1 core workflow','Outcome analytics','Email support']],['Growth','Connected customer operations',['Multiple agents','Calendar / CRM workflows','Advanced outcome tracking','Priority onboarding']],['Business','Deeper controls and integrations',['Team workflows','Advanced integrations','Custom action logic','Priority support']],['Enterprise','Specialized deployments',['Custom architecture','Security review','Deployment options','Commercial SLA options']]];

function Logo(){return <a className="logo" href="#top" aria-label="KATHYA AI home"><span className="mark">K</span><strong>KATHYA <i>AI</i></strong></a>}
function App(){
 const[menu,setMenu]=useState(false),[demo,setDemo]=useState(0),[solution,setSolution]=useState(0);
 const steps=['Listening to customer','Understanding intent','Checking connected system','Outcome ready'];
 useEffect(()=>{const f=()=>setMenu(false);window.addEventListener('resize',f);return()=>window.removeEventListener('resize',f)},[]);
 const runDemo=()=>{setDemo(1);[2,3,4].forEach((n,i)=>setTimeout(()=>setDemo(n),700*(i+1)))};
 return <div id="top">
 <header><div className="shell nav"><Logo/><nav className={menu?'open':''}>{['Product','Solutions','Industries','Integrations','Pricing','Resources'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}<a href="#signin">Sign in</a><a className="mobileCta" href="#contact">Talk to KATHYA</a></nav><a className="navCta" href="#contact">Talk to KATHYA</a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main>
 <section className="hero section" id="product"><div className="watermark">K</div><div className="shell heroGrid"><div className="heroCopy"><div className="eyebrow"><span/> CONVERSATIONAL AI FOR REAL BUSINESS ACTIONS</div><h1>Conversations that <em>complete the work.</em></h1><p>KATHYA understands customer intent, connects to business systems and moves every conversation toward a clear outcome.</p><div className="actions"><a className="primary" href="#contact">Talk to KATHYA <ArrowRight/></a><a className="textLink" href="#experience">See the workflow <ChevronRight/></a></div><div className="proof"><span>Natural voice</span><span>Business actions</span><span>Human handoff</span></div></div>
 <div className="demo" id="experience"><div className="demoTop"><span><b/> KATHYA LIVE</span><small>CONVERSATION → OUTCOME</small></div><div className="chat"><div><small>CUSTOMER</small>Can you book a demo tomorrow afternoon?</div><div className="ai"><small>KATHYA</small>{demo>=4?'I found two available times. Which works better?':'I can check availability and help you choose a time.'}</div></div><div className="steps">{steps.map((s,i)=><div className={demo>=i+1?'active':''} key={s}><b>{String(i+1).padStart(2,'0')}</b><span>{s}</span></div>)}</div><div className="signals"><span>INTENT<strong>{demo>=2?'Book demo':'—'}</strong></span><span>TOOL<strong>{demo>=3?'Calendar':'—'}</strong></span><span>STATUS<strong>{demo>=4?'Ready':'Waiting'}</strong></span></div><button className="experience" onClick={runDemo}><Play/> {demo===4?'Experience again':'Experience KATHYA'}</button></div></div></section>
 <section className="ticker"><div>VOICE <i>✦</i> KNOWLEDGE <i>✦</i> REASONING <i>✦</i> ACTIONS <i>✦</i> ANALYTICS <i>✦</i> HUMAN HANDOFF</div></section>
 <section className="section compact"><div className="shell"><div className="sectionHead"><span>HOW KATHYA WORKS</span><h2>One conversation.<br/>Real action.</h2></div><div className="flow">{['Speak','Understand','Decide','Act','Complete'].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{['Natural conversation','Intent + context','Rules + knowledge','Connected tools','Outcome captured'][i]}</p></article>)}</div></div></section>
 <section className="section" id="solutions"><div className="shell"><div className="sectionHead"><span>SOLUTIONS</span><h2>Start with the outcome.</h2><p>Configure KATHYA around the job your customers need completed.</p></div><div className="solutionLayout"><div className="solutionTabs">{solutions.map((s,i)=><button className={solution===i?'active':''} onClick={()=>setSolution(i)} key={s[0]}><span>0{i+1}</span>{s[0]}<ChevronRight/></button>)}</div><div className="solutionFeature"><span>ACTIVE WORKFLOW</span><h3>{solutions[solution][0]}</h3><p>{solutions[solution][1]}</p><div className="miniFlow"><i>Conversation</i><b>→</b><i>Intent</i><b>→</b><i>Action</i><b>→</b><i>Outcome</i></div></div></div></div></section>
 <section className="section alt" id="integrations"><div className="watermark wm2">K</div><div className="shell"><div className="sectionHead"><span>CONNECTED BUSINESS</span><h2>Fits into the systems you already use.</h2></div><div className="integrationGrid">{integrations.map(([n,I])=><article key={n}><I/><h3>{n}</h3><p>Connect KATHYA workflows to {n.toLowerCase()} when configured for your deployment.</p></article>)}</div></div></section>
 <section className="section" id="industries"><div className="shell"><div className="sectionHead"><span>INDUSTRIES</span><h2>Built around customer operations.</h2></div><div className="industryRow">{['Healthcare','Real Estate','Automotive','Hospitality','Financial Services','Home Services','E-commerce','Professional Services'].map(x=><span key={x}>{x}</span>)}</div></div></section>
 <section className="section" id="pricing"><div className="shell"><div className="sectionHead"><span>PRICING</span><h2>Start focused. Scale with usage.</h2></div><div className="plans">{plans.map((p,i)=><article className={i===1?'featured':''} key={p[0]}>{i===1&&<label>RECOMMENDED</label>}<span>{p[0]}</span><h3>Custom</h3><p>{p[1]}</p><ul>{p[2].map(x=><li key={x}><Check/>{x}</li>)}</ul><a href="#contact">{i<2?'Get started':'Contact sales'} <ArrowRight/></a></article>)}</div><p className="pricingNote">Commercial pricing depends on configured channels, usage, providers, integrations and support requirements.</p></div></section>
 <section className="section alt" id="resources"><div className="shell resource"><div><span className="tag">RESOURCES</span><h2>Learn how conversational AI moves from talk to action.</h2></div><div className="resourceCards"><article><Globe2/><h3>Voice AI Guide</h3><p>Plan a customer-facing AI workflow from conversation to outcome.</p></article><article><ShieldCheck/><h3>Trust by Design</h3><p>Design consent, data handling and human escalation into the experience.</p></article></div></div></section>
 <section className="section cta" id="contact"><div className="shell ctaBox"><div><span>READY WHEN YOU ARE</span><h2>What should KATHYA handle for your business?</h2><p>Start with one workflow. Connect the systems. Measure the outcome.</p></div><a className="primary" href="mailto:likhit@pamedlogtalent.com">Talk to KATHYA <ArrowRight/></a></div></section>
 </main>
 <footer><div className="shell footer"><Logo/><p>KATHYA AI — a technology product by PA MedLog Talent LLC.</p><span>Speak. Understand. Act.</span></div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);